/*
 * This source file was generated by the Gradle 'init' task
 */
package progetto_java;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class App {
    void createConnection() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/test_schema", "root", "PasswordUsedForMySQLRoot123!");
            System.out.println("Connection established successfully!");
        } catch (ClassNotFoundException | SQLException e) {
            Logger.getLogger (this.getClass().getName()).log (Level. SEVERE, null, e);
        }
    }

    public static void main(String[] args) {
        App newApp = new App();
        newApp.createConnection();
    }
}
